apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mercurysinglenode-nginx-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app: loadbalancer-nginx
    io.kompose.name: mercury-single-node
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfsVolumes.nginx.conf.storage }}
  volumeName: mercurysinglenode-nginx-conf-vol1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mercurysinglenode-nginx-html
  namespace: {{ .Release.Namespace }}
  labels:
    app: loadbalancer-nginx
    io.kompose.name: mercury-single-node
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfsVolumes.nginx.html.storage }}
  volumeName: mercurysinglenode-nginx-html-vol1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mercurysinglenode-certificate-center
  namespace: {{ .Release.Namespace }}
  labels:
    app: loadbalancer-nginx
    io.kompose.name: mercury-single-node
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfsVolumes.certificateCenter.storage }}
  volumeName: mercurysinglenode-certificate-center-vol1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mercurysinglenode-postgres-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgresql
    io.kompose.name: mercury-single-node
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfsVolumes.postgresDb.storage }}
  volumeName: mercurysinglenode-postgres-db-vol1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mercurysinglenode-openldap-ldap
  namespace: {{ .Release.Namespace }}
  labels:
    app: openldap
    io.kompose.name: mercury-single-node
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfsVolumes.openldap.ldap.storage }}
  volumeName: mercurysinglenode-openldap-ldap-vol1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mercurysinglenode-openldap-slapd
  namespace: {{ .Release.Namespace }}
  labels:
    app: openldap
    io.kompose.name: mercury-single-node
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfsVolumes.openldap.slapd.storage }}
  volumeName: mercurysinglenode-openldap-slapd-vol1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mercurysinglenode-poi-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: poiServer
    io.kompose.name: mercury-single-node
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfsVolumes.poiServer.storage }}
  volumeName: mercurysinglenode-poi-server-vol1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mercurysinglenode-mercury-upload
  namespace: {{ .Release.Namespace }}
  labels:
    app: mercury
    io.kompose.name: mercury-single-node
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfsVolumes.mercury.upload.storage }}
  volumeName: mercurysinglenode-mercury-upload-vol1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mercurysinglenode-mercury-lucene
  namespace: {{ .Release.Namespace }}
  labels:
    app: mercury
    io.kompose.name: mercury-single-node
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfsVolumes.mercury.lucene.storage }}
  volumeName: mercurysinglenode-mercury-lucene-vol1
