apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: {{ .Release.Namespace }}
  labels:
    app: openldap
    io.kompose.name: mercury-single-node
    io.kompose.service: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openldap
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: openldap
    spec:
      hostname: openldap
      imagePullSecrets:
        - name: "{{ .Values.image.pullSecret }}"
      containers:
        - name: openldap
          image: "{{ .Values.image.registry }}openldap:{{ .Values.image.mainTag }}"
          env:
            - name: LDAP_OLC_SUFFIX
              valueFrom:
                configMapKeyRef:
                  name: mercury-hgdb #Read from a configmap called oradb
                  key: LDAP_OLC_SUFFIX #Read the key
            - name: LDAP_ORG_DC
              valueFrom:
                configMapKeyRef:
                  name: mercury-hgdb #Read from a configmap called oradb
                  key: LDAP_ORG_DC #Read the key
            - name: LDAP_ROOT_CN
              valueFrom:
                configMapKeyRef:
                  name: mercury-hgdb #Read from a configmap called oradb
                  key: LDAP_ROOT_CN #Read the key
            - name: LDAP_ROOT_DN
              valueFrom:
                configMapKeyRef:
                  name: mercury-hgdb #Read from a configmap called oradb
                  key: LDAP_ROOT_DN #Read the key
            - name: LDAP_ROOT_PASSWD
              valueFrom:
                configMapKeyRef:
                  name: mercury-hgdb #Read from a configmap called oradb
                  key: LDAP_ROOT_PASSWD #Read the key
            - name: LDAP_TECHNICAL_USER_CN
              valueFrom:
                configMapKeyRef:
                  name: mercury-hgdb #Read from a configmap called oradb
                  key: LDAP_TECHNICAL_USER_CN #Read the key
            - name: LDAP_TECHNICAL_USER_PASSWD
              valueFrom:
                configMapKeyRef:
                  name: mercury-hgdb #Read from a configmap called oradb
                  key: LDAP_TECHNICAL_USER_PASSWD #Read the key
          ports:
            - containerPort: 389
            - containerPort: 636
          resources: {}
          volumeMounts:
            - name: mercurysinglenode-openldap
              mountPath: /var/lib/openldap
            - name: mercurysinglenode-slapd-d
              mountPath: /etc/openldap/slapd.d
      restartPolicy: Always
      volumes:
        - name: mercurysinglenode-openldap
          persistentVolumeClaim:
            claimName: mercurysinglenode-openldap-ldap
        - name: mercurysinglenode-slapd-d
          persistentVolumeClaim:
            claimName: mercurysinglenode-openldap-slapd
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: {{ .Release.Namespace }}
  labels:
    app: openldap
    io.kompose.name: mercury-single-node
    io.kompose.service: openldap
spec:
  selector:
    io.kompose.service: openldap
  ports:
    - name: "ldap"
      port: 389
      targetPort: 389
    - name: "ldaps"
      port: 636
      targetPort: 636
  type: NodePort
status:
  loadBalancer: {}
  