apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-server-node1
  namespace: {{ .Release.Namespace }}
  labels:
    app: poiServer
    io.kompose.name: mercury-single-node
    io.kompose.service: poi-server-node1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: poi-server-node1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: poi-server-node1
    spec:
      hostname: poi-server-node1
      imagePullSecrets:
        - name: "{{ .Values.image.pullSecret }}"
      containers:
        - name: poi-server-node1
          image: "{{ .Values.image.registry }}poi-server:{{ .Values.image.mainTag }}"
          env:
            - name: HGDB_NODE
              valueFrom:
                configMapKeyRef:
                  name: mercury-hgdb #Read from a configmap called oradb
                  key: HGDB_NODE #Read the key
          ports:
            - containerPort: 10090
          resources: {}
          volumeMounts:
            - name: mercurysinglenode-poi-server 
              mountPath: /opt/poi-server/data
      restartPolicy: Always
      volumes:
        - name: mercurysinglenode-poi-server
          persistentVolumeClaim:
            claimName: mercurysinglenode-poi-server
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: poi-server-node1
  namespace: {{ .Release.Namespace }}
  labels:
    app: poiServer
    io.kompose.name: mercury-single-node
    io.kompose.service: poi-server-node1
spec:
  selector:
    io.kompose.service: poi-server-node1
  ports:
    - name: "https"
      port: 10090
      targetPort: 10090
  type: NodePort
status:
  loadBalancer: {}
