version: '2'

networks:
  mercury-network:
    driver: bridge

volumes:
  nginx-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /d/mercury/nginx/conf
  nginx-html:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /d/mercury/nginx/html
  certificate_center:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /d/mercury/certificate_center
  postgres-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /d/mercury/postgres-db
  openldap:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /d/mercury/openldap
  slapd-d:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /d/mercury/slapd.d            
  poi-server:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /d/mercury/poi-server            
  mercury-upload:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /d/mercury/mercury-upload            
  mercury-lucene:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /d/mercury/mercury-lucene 
 
services:
  mercury:
    image: ibpm/mercury-lb:mercury-hgdb-3.0
    networks:
      - mercury-network
    build:
      context: .
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    links:
      - postgres-db
      - activemq
      - openldap
      - poi-server-node1
      - ehcache-node1
      - mercury-node1
    environment:
      - HGDB_NODES=${HGDB_NODES}
      - SERVER_NAME=${SERVER_NAME}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - HTTPS_PORT=${HGDB_URL_PORT}
      - COUNTRY=${COUNTRY}
      - STATE=${STATE}
      - CITY=${CITY}
      - ORG_NAME=${ORG_NAME}
      - EMAIL=${EMAIL}
    volumes: 
      - nginx-conf:/opt/nginx/conf:rw
      - nginx-html:/opt/nginx/html:rw
      - certificate_center:/opt/certificate_center:rw
    ports:
      - "1080:80"
      - "${HGDB_URL_PORT}:443"
      
  postgres-db:
    image: ibpm/postgres:mercury-hgdb-3.0
    networks:
      - mercury-network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - HGDB_USER_PASSWORD=${HGDB_USER_PASSWORD}
    volumes: 
      - postgres-db:/var/lib/postgresql/data:rw
    ports:
      - "15432:5432"
      
  activemq:
    image: ibpm/activemq:mercury-hgdb-3.0
    networks:
      - mercury-network
    environment:
      - HGDB_NODES=${HGDB_NODES}
      - POSTGRESQL_SERVER_NAME=postgres-db
      - HGDB_USER_PASSWORD=${HGDB_USER_PASSWORD}
      - MQ_ADMIN_PASSWORD=${MQ_ADMIN_PASSWORD}
      - MQ_USER_PASSWORD=${MQ_USER_PASSWORD}
    depends_on:
      - postgres-db
    ports:
      - "18161:8161"

  openldap:
    image: ibpm/openldap:mercury-hgdb-3.0
    networks:
      - mercury-network
    environment:
      - LDAP_ORG_DC=${LDAP_ORG_DC}
      - LDAP_OLC_SUFFIX=${LDAP_OLC_SUFFIX}
      - LDAP_ROOT_CN=${LDAP_ROOT_CN}
      - LDAP_ROOT_DN=cn=${LDAP_ROOT_CN},${LDAP_OLC_SUFFIX}
      - LDAP_ROOT_PASSWD=${LDAP_ROOT_PASSWD}
      - LDAP_TECHNICAL_USER_CN=${LDAP_TECHNICAL_USER_CN}
      - LDAP_TECHNICAL_USER_PASSWD=${LDAP_TECHNICAL_USER_PASSWD}
    depends_on:
      - activemq
    volumes: 
      - openldap:/var/lib/openldap:rw
      - slapd-d:/etc/openldap/slapd.d:rw
    ports:
      - "389:389"
      - "636:636"

  ehcache-node1:
    networks:
      - mercury-network
    image: ibpm/ehcache:mercury-hgdb-3.0
    environment:
      - HGDB_NODES=${HGDB_NODES}
      - HGDB_NODE=${HGDB_NODE}
      
  poi-server-node1:
    image: ibpm/poi-server:mercury-hgdb-3.0
    networks:
      - mercury-network
    environment:
      - HGDB_NODE=${HGDB_NODE}
    depends_on:
      - openldap
      - ehcache-node1
    volumes: 
      - poi-server:/opt/poi-server/data:rw
    ports:
      - "10090:10090"
    
  mercury-node1:
    networks:
      - mercury-network
    image: ibpm/mercury:mercury-hgdb-3.0.3.2.11
    environment:
      - HGDB_NODE=${HGDB_NODE}
      - HOST_NAME=mercury-node1
      - HGDB_ROLE=MASTER
      - HGDB_IS_CLUSTER=false
      - HGDB_HA_GROUP=single
      - HGDB_URL_SCHEMA=${HGDB_URL_SCHEMA}
      - HGDB_URL_HOST=${HGDB_URL_HOST}
      - HGDB_URL_PORT=${HGDB_URL_PORT}
      - POI_SERVER_NAME=poi-server-node1
      - LDAP_CONNECTION_NAME=cn=${LDAP_TECHNICAL_USER_CN},ou=Technical,${LDAP_OLC_SUFFIX}
      - LDAP_CONNECTION_PASSWD=${LDAP_TECHNICAL_USER_PASSWD}
      - LDAP_CONNECTION=ldap://openldap:389
      - LDAP_USERS_DN=ou=People,${LDAP_OLC_SUFFIX}
      - LDAP_ROLES_DN=ou=Groups,${LDAP_OLC_SUFFIX}
      - POSTGRESQL_CONNECTION=postgres-db:5432
      - POSTGRESQL_USER=mercury
      - POSTGRESQL_PASSWD=${HGDB_USER_PASSWORD}
      - ACTIVEMQ_TCP_CONNECTION=activemq:61616
      - SECURITY_TOKEN=${SECURITY_TOKEN}
      - EHCACHE_TERRACOTA_CONNECTION=ehcache-node1:9410/clustered
    depends_on:
      - poi-server-node1
    volumes: 
      - poi-server:/opt/mercury-3.0/poi-data:rw
      - mercury-upload:/opt/mercury-3.0/upload:rw
      - mercury-lucene:/opt/mercury-3.0/lucene:rw
    ports:
      - "8080:8080"
    
    